### PR TITLE
Fixed a potential panic with nil conn

### LINKED ISSUE #71: Crash running tlsx in auto-mode
### tlsx version:

dev

### Current Behavior:

Crash with auto mode

### Expected Behavior:

Scan finishes succesfully

```console
panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc8f258]
goroutine 313 [running]:\ngithub.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc001216d98, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0xc8b2b2?}})
/root/tlsx/pkg/tlsx/ztls/ztls.go:187 +0x878\ngithub.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc001216db0, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0xc00001fa98?}})
/root/tlsx/pkg/tlsx/auto/auto.go:42 +0xfd\ngithub.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc001216d68, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0x0?}})
/root/tlsx/pkg/tlsx/tlsx.go:58 +0xfd\ngithub.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc000016600, 0x0?, 0x0?)
/root/tlsx/internal/runner/runner.go:152 +0x445\ncreated by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute
/root/tlsx/internal/runner/runner.go:118 +0x65
```

### Anything else:

```
{"ip":"104.248.121.26","level":"error","msg":"Could not execute work module tlsx 2.16.0.0/12: could not run tlsx: could not wait for command to finish: exit status 2 =\u003e   \n\n  _____ _    _____  __\n |_   _| |  / __\\ \\/ /\n   | | | |__\\__ \\\u003e  \u003c \n   |_| |____|___/_/\\_\\\tv0.0.5\n\n\t\tprojectdiscovery.io\n\n[\u001b[34mWRN\u001b[0m] Use with caution. You are responsible for your actions.\n[\u001b[34mWRN\u001b[0m] Developers assume no liability and are not responsible for any misuse or damage.\npanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc8f258]\n\ngoroutine 313 [running]:\ngithub.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc001216d98, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0xc8b2b2?}})\n\t/root/tlsx/pkg/tlsx/ztls/ztls.go:187 +0x878\ngithub.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc001216db0, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0xc00001fa98?}})\n\t/root/tlsx/pkg/tlsx/auto/auto.go:42 +0xfd\ngithub.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc001216d68, {0xc003e64b90, 0xc}, {0x0, 0x0}, {0xf2041f, 0x3}, {{0x0?, 0x0?}})\n\t/root/tlsx/pkg/tlsx/tlsx.go:58 +0xfd\ngithub.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc000016600, 0x0?, 0x0?)\n\t/root/tlsx/internal/runner/runner.go:152 +0x445\ncreated by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute\n\t/root/tlsx/internal/runner/runner.go:118 +0x65\n\n","taskid":"cbp8t778j1tdoqpk4mag","time":"2022-08-09T16:49:04Z"}
```

### PR DESCRIPTION
**Pull request by Ice3man543**
Potentially closes #71

### CODE REVIEW

File: pkg/tlsx/auto/auto.go [hunk 1]
```diff
@@ -42,6 +42,9 @@ func (c *Client) ConnectWithOptions(hostname, ip, port string, options clients.C
 		ztlsResponse, ztlsErr := c.ztlsClient.ConnectWithOptions(hostname, ip, port, options)
 		if ztlsErr != nil {
 			opensslResponse, opensslError := c.opensslClient.ConnectWithOptions(hostname, ip, port, options)
+			if opensslError == openssl.ErrNotSupported {
```
Comment (Mzack9999) [inline pkg/tlsx/auto/auto.go:45]: what about `errors.Is(opensslError,openssl.ErrNotSupported)`?

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
suggesting to use `errors.Is`

**Review by Mzack9999 — APPROVED** [review]
