### PR TITLE
Fixing custom ip resolution

### LINKED ISSUE #112: Wrong IP reported in case of custom IP provided
### tlsx version:
`main|master` and `dev`

### Current Behavior:
TLSX as a library reports wrong dialed ip (fastdialer lookup is performed on the domain name and will report always the first dialed ip)

### Expected Behavior:
Custom ip should be used if provided at the following locations:
```
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/tls/tls.go#L120
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/ztls/ztls.go#L135
https://github.com/projectdiscovery/tlsx/blob/3d5172c6c493efcab4efb836e374a2b5d432e9fc/pkg/tlsx/openssl/openssl.go#L95
```

### How to reproduce
Using `issue-2141-scan-all-ips` branch in nuclei
```console
$ echo https://hackerone.com | go run . -id tls-version -sa -iv 4 -json -rl 1 -c 1 -bs 1 -v
...
[VER] Sent SSL request to hackerone.com:443
{"template":"\\ssl\\tls-version.yaml","template-url":"https://github.com/projectdiscovery/nuclei-templates/blob/master/\\ssl\\tls-version.yaml","template-id":"tls-version","info":{"name":"TLS Version","author":["pdteam"],"tags":["ssl"],"reference":null,"severity":"info"},"type":"ssl","host":"hackerone.com","matched-at":"hackerone.com","extracted-results":["tls13"],"ip":"104.16.100.52","timestamp":"2022-11-04T21:30:04.673107+01:00","matcher-status":true,"matched-line":null}
[VER] Sent SSL request to hackerone.com:443
{"template":"\\ssl\\tls-version.yaml","template-url":"https://github.com/projectdiscovery/nuclei-templates/blob/master/\\ssl\\tls-version.yaml","template-id":"tls-version","info":{"name":"TLS Version","author":["pdteam"],"tags":["ssl"],"reference":null,"severity":"info"},"type":"ssl","host":"hackerone.com","matched-at":"hackerone.com","extracted-results":["tls13"],"ip":"104.16.100.52","timestamp":"2022-11-04T21:30:04.7559573+01:00","matcher-status":true,"matched-line":null}
```

### PR DESCRIPTION
**Pull request by Mzack9999**
Closes #112

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
Not sure why; one of the IPs is getting dropped in each scan randomly. @Mzack9999 

```bash
$ echo hackerone.com | go run . -sa -iv 6 -tps -silent
hackerone.com:443 (2606:4700::6810:6334) [success]
hackerone.com:443 (2606:4700::6810:6434) [success]

$ echo hackerone.com | go run . -sa -iv 6 -tps -silent
hackerone.com:443 (2606:4700:8d73:d6bc:bac5:0:72c9:13b7) [success]

$ echo hackerone.com | go run . -sa -iv 6 -tps -silent
hackerone.com:443 (2606:4700::6810:6434) [success]
hackerone.com:443 (2606:4700::6810:6334) [success]

$ echo hackerone.com | go run . -sa -iv 6 -tps -silent
hackerone.com:443 (2606:4700:8ca3:d6bc:baca:0:72c9:13b7) [success]
```

**Comment by tarunKoyalwar** [comment]
@ehsandeep 

No reproducible locally

```sh
for i in {1..10} do;  echo hackerone.com | go run . -sa -tps -iv 6 -silent done
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]
hackerone.com:443 (2606:4700:9ad3:d6bc:bade:0:72c9:13b7) [success]

```

File: pkg/tlsx/openssl/openssl.go [hunk 1]
```diff
@@ -44,7 +44,12 @@ func New(options *clients.Options) (*Client, error) {
...
-	address := net.JoinHostPort(hostname, port)
+	var address string
+	if ip != "" || c.options.ScanAllIPs || len(c.options.IPVersion) > 0 {
+		address = net.JoinHostPort(ip, port)
+	} else {
+		address = net.JoinHostPort(hostname, port)
+	}
 
 	if c.options.ScanAllIPs || len(c.options.IPVersion) > 0 {
 		address = net.JoinHostPort(ip, port)
```
Comment (tarunKoyalwar) [inline pkg/tlsx/openssl/openssl.go:55]: seems redundant already covered in L#48

File: pkg/tlsx/tls/tls.go [hunk 2]
```diff
@@ -116,12 +117,14 @@ func (c *Client) ConnectWithOptions(hostname, ip, port string, options clients.C
 	if rawConn == nil {
 		return nil, fmt.Errorf("could not connect to %s", address)
 	}
+
 	var resolvedIP string
-	if !iputil.IsIP(hostname) {
+	if ip != "" {
+		resolvedIP = ip
+	} else if iputil.IsIP(hostname) {
+		resolvedIP = hostname
```
Comment (tarunKoyalwar) [inline pkg/tlsx/tls/tls.go:125]: Instead of handling edgecase where `ip` is passed in `hostname` field . How about verifying at beginning of function call if 

hostname is indeed a hostname and not ip
ip is valid and not a hostname 

this might solve future errors . current issue with nuclei is that we are passing hostname in both fields (ip & hostname) https://github.com/projectdiscovery/nuclei/blob/05d607642a11449262fba8d079025dc5325dec8d/v2/pkg/protocols/ssl/ssl.go#L164-L167

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]

File: pkg/tlsx/openssl/openssl.go (hunk 1 above)
Comment (Mzack9999) [reply pkg/tlsx/openssl/openssl.go:55]: nice catch - forgot to delete it after merging conditions in the if

File: pkg/tlsx/tls/tls.go (hunk 2 above)
Comment (Mzack9999) [reply pkg/tlsx/tls/tls.go:125]: @tarunKoyalwar, the `ip` parameter is only used in case of custom ip override, typically, the hostname might also contain a DNS name, and it defers to fastdialer to connect to the first responsive ip. I think here the check is legitimate as we are handling the cases:
- Custom ip provided => use that
- input was an ip => use that
- input was a hostname => retrieve the dialed ip from fastdialer

This should be addressed uniformly with https://github.com/projectdiscovery/metainput across all the tools (currently prototyped in nuclei only), as various parameters will change to a unique struct definition.

Comment (tarunKoyalwar) [reply pkg/tlsx/tls/tls.go:125]: Thanks , Got it

**Comment by Mzack9999** [comment]
@ehsandeep I think it might be due to the resolver used. In some cases, the host resolves to `2606:4700::6810:6334` and `2606:4700::6810:6434` and in others only to `2606:4700:9ad3:d6bc:bade:0:72c9:13b7`. In the first case, all two are present in the results.

**Review by tarunKoyalwar — APPROVED** [review]
